<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
<TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>BH.Engine.Adapters.SAP2000</RootNamespace>
    <OutputPath>..\Build\</OutputPath>
    <AssemblyTitle>SAP2000_Engine</AssemblyTitle>
    <Description>https://github.com/BHoM/SAP2000_Toolkit</Description>
    <Company>Buro Happold</Company>
    <Product>SAP2000_Engine</Product>
    <Copyright>Copyright © https://github.com/BHoM</Copyright>
    <AssemblyVersion>9.0.0.0</AssemblyVersion>
    <FileVersion>9.3.0.0</FileVersion>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetDir)$(TargetFileName)&quot;  &quot;C:\ProgramData\BHoM\Assemblies&quot; /Y" />
  </Target>
  <ItemGroup>
    <Reference Include="Acoustic_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Acoustic_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Adapter_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Adapter_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Analytical_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Analytical_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Architecture_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Architecture_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Dimensional_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Dimensional_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Environment_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Environment_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Geometry_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Geometry_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Geometry_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Geometry_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Graphics_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Graphics_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Humans_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Humans_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Library_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Library_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Physical_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Physical_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Physical_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Physical_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Planning_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Planning_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Results_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Results_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Serialiser_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Serialiser_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Structure_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Structure_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Structure_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Structure_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Create\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAP2000_oM\SAP2000_oM.csproj" />
  </ItemGroup>
</Project>
